# The three categories of resources (time, call, and memory) are fixed, but within each category you
# are free to monitor whatever resources you wish. The color specifications are used for plotting.

# Within each category the order is significant. The items will appear in menus, plots, and tables
# in this order.
---
time_resources:
- gc_time: '#000000'
- wait_time: '#1e90ff'
- other_time: '#b3d1f9'
- memcache_time: '#ffa500'
- redis_time: '#a41a11'
- gearman_time: '#00aa33'
- search_time: '#ff00ff'
- api_time: '#00aaaa'
- db_time: '#ff0000'
- riak_time: '#d34583'
- view_time: '#0022ff'
- total_time: '#000000'

call_resources:
- gc_calls: '#000000'
- memcache_misses: '#00dd00'
- memcache_reads: '#3488bc'
- memcache_writes: '#aec7e8'
- memcache_calls: '#ffa500'
- redis_calls: '#a41a11'
- gearman_calls: '#00aa33'
- search_calls: '#ff00ff'
- api_calls: '#00aaaa'
- db_sql_query_cache_hits: '#00ff00'
- db_calls: '#ff0000'
- riak_calls: '#d34583'

memory_resources:
- allocated_memory: '#ff00ff'
- allocated_bytes: '#ff0000'
- allocated_objects: '#0022ff'

heap_resources:
- heap_size: '#000000'
- heap_growth: '#567757'
- live_data_set_size: '#352378'

frontend_resources:
- page_time: '#000000'
- ajax_time: '#000000'
- load_time: '#352378'
- processing_time: '#b3d1f9'
- response_time: '#d34583'
- request_time: '#bcbd22'
- connect_time: '#ff0000'
- frontend_time: '#000000'

dom_resources:
- style_nodes: '#00bb11'
- script_nodes: '#00aaaa'
- html_nodes: '#bcbd22'
